apiVersion: v1
kind: Service
metadata:
  name: {{ include "zs-postgres-local.fullname" . }}
  labels:
    {{- include "zs-postgres-local.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if ne .Values.service.type "ExternalName" }}  
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  {{- else }}
  externalName: {{ .Values.dnsname }}
  {{- end }}
  selector:
    {{- include "zs-postgres-local.selectorLabels" . | nindent 4 }}
